# Create
###########################
# Create - Single - Success
POST http://localhost:5000/add HTTP/1.1
Content-Type: application/json

{
    "title": "Delete",
    "company": "Not a real company",
    "location": "Anywhere",
    "salary": 400000,
    "summary": "This is not a real job listing. Delete this later. DELETE",
    "url": "http://Dontforgettochangethiseachtime.com",
    "posted": "2022-12-13",
    "scraped": "2022-12-13T00:05:10.442112"
}


###    
# Create - Single - Failure 
# Failure - missing title
POST http://localhost:5000/add HTTP/1.1
Content-Type: application/json

{
    "company": "Not a real company",
    "location": "Anywhere",
    "salary": 40000,
    "summary": "This is not a real job listing. Delete this later. DELETE",
    "url": "http://Dontforgettochangethiseachtime.com",
    "posted": "2022-12-13",
    "scraped": "2022-12-13T00:05:10.442112"
}


###
# Create - Many - Success
POST http://localhost:5000/add HTTP/1.1
Content-Type: application/json

[
    {
        "title": "Delete",
        "company": "Not a real company",
        "location": "Anywhere",
        "salary": 400000,
        "summary": "This is not a real job listing. Delete this later. DELETE",
        "url": "http://Dontforgettochangethiseachtime.com",
        "posted": "2022-12-13",
        "scraped": "2022-12-13T00:05:10.442112"
    },
    {
        "title": "Delete",
        "company": "Not a real company",
        "location": "Anywhere",
        "salary": 400000,
        "summary": "This is not a real job listing. Delete this later. DELETE",
        "url": "http://Dontforgettochangethiseachtime2.com",
        "posted": "2022-12-13",
        "scraped": "2022-12-13T00:05:10.442112"
    }
]

###
# Create - Many - Single Failure
# Failure - timestamp instead of date
POST http://localhost:5000/add HTTP/1.1
Content-Type: application/json

[
    {
        "title": "Delete",
        "company": "Not a real company",
        "location": "Anywhere",
        "salary": 400000,
        "summary": "This is not a real job listing. Delete this later. DELETE",
        "url": "http://Dontforgettochangethiseachtime.com",
        "posted": "2022-12-13",
        "scraped": "2022-12-13T00:05:10.442112"
    },
    {
        "title": "Delete",
        "company": "Not a real company",
        "location": "Anywhere",
        "salary": 400000,
        "summary": "This is not a real job listing. Delete this later. DELETE",
        "url": "http://Dontforgettochangethiseachtime2.com",
        "posted": "2022-12-13T00:05:10.442112",
        "scraped": "2022-12-13T00:05:10.442112"
    }
]

###
# Create - Many - Many failure
# Failure: integer for string type: company
# Failure: invalid url
POST http://localhost:5000/add HTTP/1.1
Content-Type: application/json

[
    {
        "title": "Delete",
        "company": 25,
        "location": "Anywhere",
        "salary": 400000,
        "summary": "This is not a real job listing. Delete this later. DELETE",
        "url": "http://Dontforgettochangethiseachtime.com",
        "posted": "2022-12-13",
        "scraped": "2022-12-13T00:05:10.442112"
    },
    {
        "title": "Delete",
        "company": "Not a real company",
        "location": "Anywhere",
        "salary": 400000,
        "summary": "This is not a real job listing. Delete this later. DELETE",
        "url": "http://Dontforgettochangethiseachtime2",
        "posted": "2022-12-13",
        "scraped": "2022-12-13T00:05:10.442112"
    }
]

###
# Read

# Update

# Delete